# Ansible-pipeline

trigger:
- main

pool:
  name: 'My-Self'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo installing and configuring nginx on the server mentioned on ansible hosts file.
    ansible-playbook nginx.yaml
